Models/Finances/Bills.cs
using System;
using AfyaHMIS.Models.Administrations;
using AfyaHMIS.Models.Registrations;
using AfyaHMIS.Service;

namespace AfyaHMIS.Models.Finances
{
    public class Bills
    {
        public static IFinanceService IFinanceService = new FinanceService();

        public long Id { get; set; }
        public string Date { get; set; }
        public Visit Visit { get; set; }
        public BillingFlag Flag { get; set; }
        public Department Department { get; set; }
        public double Amount { get; set; }
        public double Paid { get; set; }
        public double Waiver { get; set; }
        public double Balance { get; set; }
        public string WaiverReason { get; set; }

        public DateTime CreatedOn { get; set; }
        public DateTime? WaivedOn { get; set; }
        public DateTime? ProcessedOn { get; set; }
        public DateTime? WaivedApprovedOn { get; set; }

        public Users CreatedBy { get; set; }
        public Users WaivedBy { get; set; }
        public Users ProcessedBy { get; set; }
        public Users WaivedApprovedBy { get; set; }
        public string Notes { get; set; }

        public Bills() {
            Id = 0;
            Date = DateTime.Now.ToString("dd/MM/yyyy");
            Visit = new Visit();
            Flag = new BillingFlag();
            Department = new Department();
            Amount = 0;
            Paid = 0;
            Waiver = 0;
            Balance = 0;
            WaiverReason = "";

            CreatedOn = DateTime.Now;

            CreatedBy = new Users();
            WaivedBy = new Users();
            ProcessedBy = new Users();
            WaivedApprovedBy = new Users();
            Notes = "";
        }

        public bool IsProcessed() {
            return IFinanceService.GetBillProcessingStatus(this);
        }

        public Bills Save() {
            return IFinanceService.SaveBill(this);
        }

        public Bills UpdateWaiver() {
            return IFinanceService.UpdateBillWaiver(this);
        }

        public Bills UpdateProcess() {
            return IFinanceService.UpdateBillProcess(this);
        }

        public Bills SetAutoFlag() {
            return IFinanceService.UpdateBillsAutoFlag(this);
        }
    }
}

Models/Finances/Invoice.cs
using System;
using System.Collections.Generic;
using AfyaHMIS.Models.Patients;
using AfyaHMIS.Service;

namespace AfyaHMIS.Models.Finances
{
    public class Invoice
    {
        private IFinanceService IFinanceService = new FinanceService();

        public long Id { get; set; }
        public string Date { get; set; }
        public Patient Patient { get; set; }
        public BillingFlag Flag { get; set; }
        public double Amount { get; set; }
        public double Paid { get; set; }
        public double Balance { get; set; }
        public Users CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string Notes { get; set; }

        public Invoice() {
            Id = 0;
            Patient = new Patient();
            Flag = new BillingFlag();
            Amount = 0;
            Paid = 0;
            Balance = 0;
            CreatedBy = new Users();
            CreatedOn = DateTime.Now;
            Notes = "";
        }

        public Invoice Save() {
            return IFinanceService.SaveInvoice(this);
        }

        public Invoice SetAutoFlag() {
            return IFinanceService.SetInvoiceAutoFlag(this);
        }

        public List<Bills> GetBills() {
            return IFinanceService.GetBills(this);
        }
    }
}

Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using AfyaHMIS.Models;
using AfyaHMIS.Models.Finances;
using AfyaHMIS.Service;
using AfyaHMIS.ViewModel;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AfyaHMIS.Controllers
{
    [Authorize]
    public class BillingController : Controller
    {
        private readonly IFinanceService IFinanceService;
        private readonly IPatientService IPatientService;

        [BindProperty]
        public BillingBillViewModel BillingModel { get; set; }

        [BindProperty]
        public BillingInvoiceViewModel InvoiceModel { get; set; }

        public BillingController(IFinanceService finance, IPatientService patient) {
            IFinanceService = finance;
            IPatientService = patient;
        }

        [Route("/billing/")]
        public IActionResult Index() {
            return View();
        }

        [Route("/billing/cashier/")]
        public IActionResult Cashier(BillingCashierViewModel model, string error = "") {
            model.Bills = IFinanceService.GetBillingCashierQueue(DateTime.Now, DateTime.Now, new BillingFlag());
            if (error.Equals("1043"))
                model.Message = "Load failed. The patient was not found";
            if (error.Equals("4509"))
                model.Message = "Load failed. The date passed was invalid";

            return View(model);
        }

        [Route("/billing/bill")]
        public IActionResult Bill(string p, string date, BillingBillViewModel model)
        {
            model.Patient = IPatientService.GetPatient(p);
            if (model.Patient == null)
                return LocalRedirect("/billing/cashier?error=1043");

            try {
                model.Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }
            catch (Exception) {
                return LocalRedirect("/billing/cashier?error=4509");
            }

            model.Invoices = IFinanceService.GetInvoices(model.Patient);
            model.Pending = IFinanceService.GetBills(model.Patient, null, null, null, new BillingFlag());
            model.Departments = IFinanceService.GetBillsDepartments(model.Patient, new BillingFlag());
            return View(model);
        }

        [Route("/billing/bill/process")]
        public IActionResult BillProcess(string p, string date, string bills, BillingBillViewModel model)
        {
            model.Patient = IPatientService.GetPatient(p);

            if (model.Patient == null)
                return LocalRedirect("/billing/cashier?error=1043");
            try {
                model.Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }
            catch (Exception) {
                return LocalRedirect("/billing/cashier?error=4509");
            }

            List<BillsItem> items = IFinanceService.GetBillsItems(bills);
            foreach(var itm in items) {
                model.Items.Add(new InvoiceDetails {
                    Checked = true,
                    Item = itm
                });
            }

            model.Invoice.Patient = model.Patient;
            model.Bills = bills;

            return View(model);
        }

        [Route("/billing/invoice")]
        public IActionResult Invoice(long qp, BillingInvoiceViewModel model, string error = "", string amts = "") {
            model.Invoice = IFinanceService.GetInvoice(qp);
            model.Details = IFinanceService.GetInvoiceDetails(model.Invoice);
            model.Amount = Convert.ToInt64(model.Invoice.Paid).ToWords().Transform(To.TitleCase).Replace("And", "and");
            model.Tendered = IFinanceService.GetPaymentSummary(model.Invoice);
            model.Modes = IFinanceService.GetBillingModeIEnumerable();

            if (error.Equals("4501"))
                model.Message = "Invoice Payment of KES " + amts + " is More than than the outstanding Invoice Balance";

            return View(model);
        }

        public bool CancelBillItems(int idnt, string items, string notes) {
            Bills bill = new Bills { Id = idnt };
            Users user = new Users { Id = long.Parse(HttpContext.User.FindFirst(ClaimTypes.Actor).Value) };

            List<string> Items = items.Split(new string[] { ",", " " }, StringSplitOptions.RemoveEmptyEntries).ToList();
            foreach (var id in Items) {
                BillsItem item = new BillsItem {
                    Id = Convert.ToInt64(id),
                    Bill = bill,
                    VoidedBy = user,
                    VoidedReason = notes
                };

                item.Void();
            }

            bill.ProcessedBy = user;
            bill.SetAutoFlag();

            return true;
        }

        [HttpPost]
        public IActionResult CreateInvoice()
        {
            Users user = new Users { Id = long.Parse(HttpContext.User.FindFirst(ClaimTypes.Actor).Value) };
            Invoice invoice = BillingModel.Invoice;
            invoice.CreatedBy = user;
            invoice.Flag = new BillingFlag { Id = Constants.FLAG_PROCESS };
            invoice.Save();

            foreach (var itd in BillingModel.Items) {
                if (itd.Checked) {
                    itd.Invoice = invoice;
                    itd.CreatedBy = user;
                    itd.Save();
                }
                else {
                    itd.Remove();
                }

                Bills bill = itd.Item.Bill;
                bill.SetAutoFlag();
            }

            return LocalRedirect("/billing/invoice/?qp=" + invoice.Id);
        }

        [HttpPost]
        public IActionResult PostInvoicePayments()
        {
            Users user = new Users { Id = long.Parse(HttpContext.User.FindFirst(ClaimTypes.Actor).Value) };
            Invoice invoice = IFinanceService.GetInvoice(InvoiceModel.Invoice.Id);
            InvoicePayment payment = InvoiceModel.Payment;

            if (payment.Amount > invoice.Balance)
                return LocalRedirect("/billing/invoice/?qp=" + invoice.Id + "&error=4501&amts=" + payment.Amount);

            payment.Invoice = invoice;
            payment.CreatedBy = user;
            payment.Notes = "N/A";
            payment.Save();

            foreach (var details in InvoiceModel.Payments) {
                if (details.Amount.Equals(0))
                    continue;

                details.Payment = payment;
                details.Save();
            }

            invoice.Paid += payment.Amount;
            invoice.Balance += payment.Amount;
            invoice.SetAutoFlag();

            return LocalRedirect("/billing/invoice/?qp=" + invoice.Id);
        }

        public bool GetBillProcessingStatus(int idnt) {
            return new Bills { Id = idnt }.IsProcessed();
        }

        public JsonResult GetBillingCashierQueue(string start, string stop, string flag = "") {
            BillingFlag bf = null;
            if (!string.IsNullOrEmpty(flag) && long.TryParse(flag, out long dblFlag)) {
                bf = new BillingFlag {
                    Id = dblFlag
                };
            }

            return Json(IFinanceService.GetBillingCashierQueue(DateTime.ParseExact(start, "dd/MM/yyyy", CultureInfo.InvariantCulture), DateTime.ParseExact(stop, "dd/MM/yyyy", CultureInfo.InvariantCulture), bf));
        }

        public JsonResult GetBillsItems(int idnt, bool process = false, bool viod = true) {
            return Json(IFinanceService.GetBillsItems(new Bills { Id = idnt }, viod, process));
        }
    }
}

Views/Billing/BillProcess.cshtml
@model AfyaHMIS.ViewModel.BillingBillViewModel;
@{
    ViewData["Title"] = "Process Bills";
}

<script src="~/js/billing-bill-process.js"></script>


<link rel="stylesheet" type="text/css" href="~/css/pages/app-ecommerce-shop.css">
<style>
    div.invoice-header{
        border-top: 1px solid #f8f8f8;
    }

    div.invoice-header > div > div > span {
        display: inline-block;
        width: 100px;
        font-weight: 800;
    }
</style>

<div class="content-detached content-left">
    <div class="content-body">
        <div class="shop-content-overlay"></div>

        <section id="ecommerce-searchbar">
            <div class="row mt-0">
                <div class="col-sm-12">
                    <fieldset class="form-group position-relative">
                        <input type="text" class="form-control search-product pl-2" id="iconLeft5" placeholder="Filter Bills Items">
                        <div class="form-control-position">
                            <i class="feather icon-search"></i>
                        </div>
                    </fieldset>
                </div>
            </div>
        </section>

        <section class="">
            <div class="card">
                <div class="card-body">
                    <div id="invoice-company-details" class="row">
                        <div class="col-sm-6 col-12 text-left pt-0">
                            <div class="media pt-0">
                                <img src="~/images/logo/logo-full.jpg"  width="200" alt="company logo">
                            </div>
                        </div>
                        <div class="col-sm-6 col-12 text-right pt-0">
                            <div class="invoice-details">
                                <h6>MEDIFORTE HOSPITAL KISII</h6>
                                <h6>P.O. BOX 12384 - 00600,<br/>KISII, KENYA.</h6>
                            </div>
                            <h1 class="mb-0">Invoice</h1>
                        </div>

                        <div class="mt-1 pt-1 pr-0 col-12 row invoice-header">
                            <div class="col-12 col-sm-6 col-lg-4">
                                <div><span>PATIENT ID: </span> @(Model.Patient.Identifier)</div>
                                <div><span>NAMES: </span> @(Model.Patient.Person.Name)</div>
                            </div>
                            <div class="col-12 col-sm-6 col-lg-4 text-center">
                                <div><span>GENDER: </span> @(Model.Patient.Person.Gender == "m" ? "MALE" : (Model.Patient.Person.Gender == "f" ? "FEMALE" : "OTHERS"))</div>
                                <div><span>PT AGE : </span> @(Model.Patient.Age)</div>
                            </div>
                            <div class="col-12 col-sm-6 col-lg-4 text-right pr-0">
                                <div><span>INVOICE NO: </span> 00/0000</div>
                                <div><span>INV DATE : </span> @DateTime.Now.ToString("dd/MM/yyyy")</div>
                            </div>
                        </div>
                    </div>
                </div>

                @using (Html.BeginForm("CreateInvoice", "Billing", FormMethod.Post, new { @class="card-content invoice-form", autocomplete = "off" }))
                {
                    <table id="invoice-bill-table" class="table table-hover-animation mb-0">
                        <thead>
                            <tr>
                                <th width="1" scope="col" class="pl-2">
                                    <span class="vs-checkbox-con vs-checkbox-primary">
                                        <input class="th-check-all" type="checkbox" checked>
                                        <span class="vs-checkbox">
                                            <span class="vs-checkbox--check">
                                                <i class="vs-icon feather icon-check"></i>
                                            </span>
                                        </span>
                                    </span>
                                </th>
                                <th scope="col">CODE</th>
                                <th scope="col">DESCRIPTION</th>
                                <th scope="col">BILL</th>
                                <th scope="col" class="text-right">PRICE</th>
                                <th scope="col" class="text-right">QTY</th>
                                <th scope="col" class="text-right">AMOUNT</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int ix = 0; ix < Model.Items.Count; ix++) 
                            {
                                <tr>
                                    <td width="1" scope="row" class="pl-2">
                                        <span class="vs-checkbox-con vs-checkbox-primary">
                                            @Html.CheckBoxFor(model => Model.Items[ix].Checked, new { @class = "check-line"} )
                                            <span class="vs-checkbox">
                                                <span class="vs-checkbox--check">
                                                    <i class="vs-icon feather icon-check"></i>
                                                </span>
                                            </span>
                                        </span>
                                    </td>
                                    <td>@Model.Items[ix].Item.Service.Code</td>
                                    <td>@Model.Items[ix].Item.Service.Name</td>
                                    <td>
                                        @Model.Items[ix].Item.Bill.Id
                                        @Html.HiddenFor(model => Model.Items[ix].Item.Id)
                                        @Html.HiddenFor(model => Model.Items[ix].Item.Bill.Id)
                                    </td>
                                    <td class="text-right">@string.Format("{0:N2}", Model.Items[ix].Item.Price)</td>
                                    <td class="text-right">@string.Format("{0:N2}", Model.Items[ix].Item.Quantity)</td>
                                    <td class="text-right">@string.Format("{0:N2}", (Model.Items[ix].Item.Price * Model.Items[ix].Item.Quantity))</td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th width="1" scope="row" class="pl-2">
                                    <span class="vs-checkbox-con vs-checkbox-primary">
                                        <input class="tf-check-summary" type="checkbox" disabled>
                                        <span class="vs-checkbox">
                                            <span class="vs-checkbox--check">
                                                <i class="vs-icon feather icon-check"></i>
                                            </span>
                                        </span>
                                    </span>
                                </th>
                                <th colspan="4">INVOICE SUMMARY</th>
                                <th class="text-right count-field">0.00</th>
                                <th class="text-right summs-field">0.00</th>
                            </tr>
                        </tfoot>
                    </table>

                    <div class="text-right m-1 mb-3">
                        <button class="btn btn-save btn-outline-primary pointer"><i class="feather icon-save"></i> SAVE</button>
                    </div>

                    @Html.HiddenFor(model => Model.Invoice.Patient.Id)
                    @Html.HiddenFor(model => Model.Invoice.Patient.Uuid)
                }
            </div>
        </section>
    </div>
</div>

<div class="sidebar-detached sidebar-right">
    <div class="sidebar">
        <div class="card col-sm-12" style="width:260px">
            <div class="card-body">
                <div class="multi-range-price">
                    <div class="multi-range-title pb-75">
                        <h6 class="filter-title mb-0">Invoices Actions</h6>
                    </div>
                    <ul class="list-unstyled price-range" id="price-range">
                        <li>
                            <span class="vs-radio-con vs-radio-primary py-25">
                                <input type="radio" name="price-range" checked value="false">
                                <span class="vs-radio">
                                    <span class="vs-radio--border"></span>
                                    <span class="vs-radio--circle"></span>
                                </span>
                                <span class="ml-50">Check All</span>
                            </span>
                        </li>
                        <li>
                            <span class="vs-radio-con vs-radio-primary py-25">
                                <input type="radio" name="price-range" value="false">
                                <span class="vs-radio">
                                    <span class="vs-radio--border"></span>
                                    <span class="vs-radio--circle"></span>
                                </span>
                                <span class="ml-50">Uncheck All</span>
                            </span>
                        </li>
                    </ul>
                </div>

                <hr />
                <div id="clear-filters">
                    <button class="btn btn-block btn-primary">INVOICE ALL</button>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Billing/Cashier.cshtml
@model AfyaHMIS.ViewModel.BillingCashierViewModel;
@{
    ViewData["Title"] = "Cashier";
}

<script src="~/vendors/js/tables/datatable/pdfmake.min.js"></script>
<script src="~/vendors/js/tables/datatable/vfs_fonts.js"></script>
<script src="~/vendors/js/tables/datatable/datatables.min.js"></script>
<script src="~/vendors/js/tables/datatable/datatables.buttons.min.js"></script>
<script src="~/vendors/js/tables/datatable/buttons.html5.min.js"></script>
<script src="~/vendors/js/tables/datatable/buttons.print.min.js"></script>
<script src="~/vendors/js/tables/datatable/buttons.bootstrap.min.js"></script>
<script src="~/vendors/js/tables/datatable/datatables.bootstrap4.min.js"></script>

<script src="~/vendors/js/pickers/pickadate/picker.js"></script>
<script src="~/vendors/js/pickers/pickadate/picker.date.js"></script>
<script src="~/vendors/js/pickers/pickadate/legacy.js"></script>

<script src="~/js/billing-cashier.js"></script>

<link rel="stylesheet" type="text/css" href="~/vendors/css/pickers/pickadate/pickadate.css">
<link rel="stylesheet" type="text/css" href="~/vendors/css/tables/datatable/datatables.min.css">
<style>
    div.search-list div.fields {
        padding: 0 7px;
    }
    .card .card-header {
        padding-bottom: 0px!important;
    }
    div.dataTables_length,
    div.dataTables_filter {
        display: none;
    }
    .picker {
        width: 150%;
        margin-top: -15px;
        text-align: left;
        position: absolute;
        top: 100%;
        z-index: 990;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
</style>

<div class="content-body">
    <section class="users-list-wrapper">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Billing Cashier</h4>
                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="feather icon-chevron-down"></i></a></li>
                        <li><a data-action=""><i class="feather icon-rotate-cw get-queue pointer"></i></a></li>
                        <li><a data-action=""><i class="feather icon-x"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-content collapse show">
                <div class="card-body" style="padding-top:5px;padding-bottom:0px;">
                    <div class="users-list-filter">
                        <form id="search-form" autocomplete = "off">
                            <div class="row search-list">
                                <div class="fields col-12 col-sm-6 col-lg-2">
                                    <fieldset class="form-group has-icon-left">
                                        <label for="users-list-role">Start Date</label>
                                        <input type="text" class="form-control pickadate" id="queue-start" placeholder="DD/MM/YYYY" value="@(Model.Date)" />
                                        <div class="form-control-position">
                                            <i class="feather icon-calendar"></i>
                                        </div>
                                    </fieldset>
                                </div>
                                <div class="fields col-12 col-sm-6 col-lg-2">
                                    <fieldset class="form-group has-icon-left">
                                        <label for="users-list-status">End Date</label>
                                        <input type="text" class="form-control pickadate" id="queue-stop" placeholder="DD/MM/YYYY" value="@(Model.Date)" />
                                        <div class="form-control-position">
                                            <i class="feather icon-calendar"></i>
                                        </div>
                                    </fieldset>
                                </div>
                                <div class="fields col-12 col-sm-6 col-lg-2">
                                    <fieldset class="form-group has-icon-left">
                                        <label for="users-list-status">Status</label>
                                        <select class="form-control pickadata" id="queue-flag">
                                            <option value="">All Bills</option>
                                            <option value="0" selected>Pending</option>
                                            <option value="1">Processed</option>
                                            <option value="2">Completed</option>
                                            <option value="99">Cancelled</option>
                                        </select>
                                        <div class="form-control-position">
                                            <i class="feather icon-clock"></i>
                                        </div>
                                    </fieldset>
                                </div>
                                <div class="fields col-12 col-sm-6">
                                    <fieldset class="form-group has-icon-left">
                                        <label for="users-list-status">Filter</label>
                                        <input type="text" class="form-control" id="queue-filter" placeholder="Filter" />
                                        <div class="form-control-position">
                                            <i class="feather icon-search"></i>
                                        </div>
                                    </fieldset>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="top-side-up">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body card-dashboard" style="padding-top:10px">
                            <div class="table-responsive">
                                <table id="billing-queue-table" class="table zero-configuration">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>DATE</th>
                                            <th>IDENTIFIER</th>
                                            <th>NAMES</th>
                                            <th>AGE</th>
                                            <th>GENDER</th>
                                            <th>STATUS</th>
                                            <th>AMOUNT</th>
                                            <th>ACTION</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var bill in Model.Bills) {
                                            <tr>
                                                <td>@bill.Id</td>
                                                <td>@bill.Date</td>
                                                <td>@bill.Visit.Patient.Identifier</td>
                                                <td><a href="/patients/@(bill.Visit.Patient.Uuid)">@bill.Visit.Patient.Person.Name</a></td>
                                                <td>@bill.Visit.Patient.Age</td>
                                                <td>@bill.Visit.Patient.Person.Gender</td>
                                                <td>@bill.Flag.Name</td>
                                                <td>@string.Format("{0:N}", bill.Amount)</td>
                                                <td>&nbsp; <a href="/billing/bill?p=@(bill.Visit.Patient.Uuid)&date=@(bill.Date)"><i class="feather icon-airplay td-action"></i></a> <a class="pointer redirect-link" data-uuid="@(bill.Visit.Patient.Uuid)" data-date="@(bill.Date)"> <i class="feather icon-x danger td-action"></i></a></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Views/Billing/Index.cshtml
@{
    ViewData["Title"] = "Billing";
}